"""General Execution: deterministic execution substrate for bounded authorized work."""

from .adapter import (
    AdapterDispatchRequest,
    AdapterError,
    AdapterReceipt,
    InvocationBundle,
    ProviderObservation,
    REFERENCE_CAPABILITY,
    REFERENCE_EVIDENCE,
    REFERENCE_TASK_KIND,
    admit_observation,
    build_dispatch_request,
    make_reference_observation,
    reference_runner,
    verify_dispatch_request,
    verify_invocation_bundle,
)
from .asp_transition import (
    AspTransitionError,
    PassiveWakeAdmission,
    PortfolioTransitionResult,
    TransitionAuthorityGrant,
    admit_passive_wake,
    apply_active_transition,
)
from .canonical import canonical_json, sha256_digest, stable_id
from .asp_transition_engine import (
    AspTransitionApplication,
    AspTransitionError as SignalAspTransitionError,
    PassiveWakeAdmission as SignalPassiveWakeAdmission,
    PassiveWakeSignal,
    admit_passive_wake as admit_passive_wake_signal,
    apply_asp_transition,
)
from .core_rehearsal import (
    CoreRehearsalAssertion,
    CoreRehearsalError,
    CoreRehearsalReport,
    REQUIRED_CORE1_ASSERTIONS,
    build_core_rehearsal_report,
)
from .core_verification import (
    CoreVerificationAdmissionError,
    CoreVerificationManifest,
    VERCEL_CORE_VERIFIER_REF,
    admit_vercel_core_verification,
)
from .capacity import (
    CapacityError,
    CapacityLease,
    CapacityLeaseGrant,
    CapacityRelease,
    CapacityReleaseGrant,
    CapacityTransition,
    CapacityTransitionRecord,
    RunnerCapacityState,
    commit_capacity_reservation,
    commit_outcome_release,
    commit_revocation_release,
    initialize_capacity_state,
    propose_capacity_reservation,
    propose_outcome_release,
    propose_revocation_release,
    record_capacity_transition,
    release_capacity_for_outcome,
    release_capacity_for_revocation,
    reserve_capacity,
    verify_active_lease_grant,
    verify_capacity_release_grant,
    verify_capacity_state,
    verify_capacity_transition_record,
)
from .conformance import (
    AttestedResubmissionPermit,
    ConformanceError,
    ProviderConformanceCaseResult,
    ProviderConformanceEvidence,
    ProviderContractAttestation,
    attest_provider_contract,
    authorize_attested_resubmission,
    verify_attested_resubmission_permit,
    verify_provider_attestation,
)
from .conformance_harness import (
    ConformanceHarnessError,
    ConformanceLookupResult,
    ConformanceSubmitResult,
    ProviderConformanceRun,
    ProviderConformanceTarget,
    ReferenceConformanceTarget,
    run_provider_conformance,
)
from .dispatch import (
    DispatchIntent,
    DispatchIntentError,
    DispatchIntentState,
    DispatchPermit,
    DispatchRecoveryItem,
    DispatchRecoveryReport,
    SqliteDispatchIntentStore,
    deserialize_dispatch_state,
    dispatch_state_from_dict,
    dispatch_state_to_dict,
    initial_dispatch_state,
    prepare_dispatch_intent,
    recover_dispatch_after_restart,
    serialize_dispatch_state,
    verify_dispatch_permit,
    verify_dispatch_recovery,
)
from .dispatch_guard import (
    LiveDispatchPermit,
    authorize_live_dispatch,
    verify_live_dispatch_permit,
)
from .durable import (
    DurableCapacityError,
    DurableCapacityHead,
    RecoveredLease,
    RestartRecoveryReport,
    SqliteCapacityHeadStore,
    capacity_snapshot,
    capacity_state_from_dict,
    capacity_state_to_dict,
    deserialize_capacity_snapshot,
    recover_capacity_after_restart,
    serialize_capacity_snapshot,
    verify_restart_recovery,
)
from .execution_checkpoint import (
    CheckpointEvidence,
    ExecutionCheckpoint,
    ExecutionCheckpointError,
    checkpoint_from_dict,
    checkpoint_to_dict,
    deserialize_checkpoint,
    serialize_checkpoint,
)
from .ledger import ExecutionLedger, LedgerEvent, append_event, verify_ledger
from .models import (
    ArtifactRef,
    DispatchPlan,
    ExecutionSession,
    ExecutionSpec,
    ResultEnvelope,
    RunnerCapabilities,
    RunnerRegistry,
)
from .portfolio_persistence import (
    DurablePortfolioHead,
    PortfolioPersistenceError,
    PortfolioRecoveryReport,
    SqlitePortfolioHeadStore,
    deserialize_portfolio_snapshot,
    portfolio_snapshot,
    recover_portfolio_after_restart,
    serialize_portfolio_snapshot,
    verify_portfolio_recovery,
)
from .portfolio_state import (
    PortfolioBlocker,
    PortfolioEntry,
    PortfolioState,
    PortfolioStateError,
    WakeCondition,
    deserialize_portfolio_state,
    portfolio_state_from_dict,
    portfolio_state_to_dict,
    serialize_portfolio_state,
)
from .observed import (
    DurableObservedOutcome,
    ObservedOutcomeReleaseRecovery,
    SqliteDurableObservedOutcomeStore,
    release_observed_capacity_after_restart,
)
from .physical import (
    DuplicatePhysicalAttempt,
    FAILURE_TRANSPORT_STATUSES,
    PhysicalAttemptAuthorization,
    PhysicalAttemptError,
    PhysicalAttemptRecord,
    PhysicalObservation,
    PhysicalOutcomeBundle,
    PhysicalReceipt,
    VALID_TRANSPORT_STATUSES,
    admit_physical_observation,
    authorize_physical_attempt,
    authorize_retry,
    identify_duplicate_physical_attempt,
    observe_completed,
    observe_failure,
    record_duplicate_physical_attempt,
    record_physical_attempt,
    verify_physical_attempt_record,
    verify_physical_outcome,
    verify_retry_chain,
)
from .physical_wire import (
    PHYSICAL_OUTCOME_WIRE_SCHEMA,
    PhysicalOutcomeCodecError,
    deserialize_physical_outcome,
    physical_outcome_from_dict,
    physical_outcome_to_dict,
    serialize_physical_outcome,
)
from .planner import plan_execution, verify_plan
from .provenance import InvocationRecord, record_invocation, verify_invocation_record
from .reconciliation import (
    ProviderReconciliationContract,
    ProviderReconciliationEvidence,
    ProviderReconciliationObservation,
    ProviderReconciliationQuery,
    ReconciliationDecision,
    ReconciliationError,
    admit_reconciliation_observation,
    create_reconciliation_query,
    decide_reconciliation,
)
from .recovery_driver import RecoveryDriverError, RecoveryDriverResult, apply_recovery_step
from .resume_tick import (
    CoreVerificationReceipt,
    CoreVerificationRequirement,
    ResumeTickError,
    ResumeTickObservation,
    ResumeTickResult,
    resume_tick,
)
from .retry_authority import (
    FailureObservation,
    RetryAuthorityError,
    RetryDecision,
    RetryPolicy,
    decide_retry,
)
from .session import SessionError, bind_session, revoke_session, start_session, submit_result
from .session_recovery import (
    SessionRecoveryError,
    SessionRecoveryProjection,
    project_session_after_restart,
)
from .transition_policy import (
    TransitionPolicy,
    TransitionPolicyError,
    TransitionRule,
    deserialize_transition_policy,
    match_transition_rule,
    serialize_transition_policy,
    transition_policy_from_dict,
    transition_policy_to_dict,
)
from .verification_escalation import (
    PROJECT_ASSURANCE_SYSTEM,
    RED_TEAM_SYSTEM,
    IndependentVerificationRequest,
    IndependentVerificationResponse,
    RedTeamEscalationRequest,
    RedTeamResponse,
    VerificationAdmission,
    VerificationEscalationError,
    admit_independent_verification,
    admit_red_team_response,
    build_verification_observation,
    prepare_independent_verification,
    prepare_red_team_escalation,
)
from .vercel_sandbox import (
    GENERAL_EXECUTION_REPOSITORY_URL,
    VERCEL_SANDBOX_PROVIDER,
    VERCEL_SANDBOX_RUNTIME,
    SandboxCommandEvidence,
    VercelSandboxConformanceError,
    VercelSandboxConformanceRun,
    VercelSandboxConformanceSpec,
    run_vercel_sandbox_conformance,
    verify_vercel_sandbox_conformance_run,
)

__all__ = [
    "AdapterDispatchRequest",
    "AdapterError",
    "AdapterReceipt",
    "ArtifactRef",
    "AspTransitionApplication",
    "AspTransitionError",
    "AttestedResubmissionPermit",
    "CapacityError",
    "CapacityLease",
    "CapacityLeaseGrant",
    "CapacityRelease",
    "CapacityReleaseGrant",
    "CapacityTransition",
    "CapacityTransitionRecord",
    "CoreVerificationReceipt",
    "CoreVerificationAdmissionError",
    "CoreRehearsalAssertion",
    "CoreRehearsalError",
    "CoreRehearsalReport",
    "CoreVerificationRequirement",
    "CoreVerificationManifest",
    "ConformanceError",
    "ConformanceHarnessError",
    "ConformanceLookupResult",
    "CheckpointEvidence",
    "ConformanceSubmitResult",
    "DispatchIntent",
    "DispatchIntentError",
    "DispatchIntentState",
    "DispatchPermit",
    "DispatchPlan",
    "DispatchRecoveryItem",
    "DispatchRecoveryReport",
    "DuplicatePhysicalAttempt",
    "DurableCapacityError",
    "DurableCapacityHead",
    "DurableObservedOutcome",
    "DurablePortfolioHead",
    "ExecutionCheckpoint",
    "ExecutionCheckpointError",
    "ExecutionLedger",
    "ExecutionSession",
    "ExecutionSpec",
    "FAILURE_TRANSPORT_STATUSES",
    "FailureObservation",
    "GENERAL_EXECUTION_REPOSITORY_URL",
    "InvocationBundle",
    "InvocationRecord",
    "LedgerEvent",
    "LiveDispatchPermit",
    "ObservedOutcomeReleaseRecovery",
    "PHYSICAL_OUTCOME_WIRE_SCHEMA",
    "PhysicalAttemptAuthorization",
    "PhysicalAttemptError",
    "PhysicalAttemptRecord",
    "PhysicalObservation",
    "PhysicalOutcomeBundle",
    "PhysicalOutcomeCodecError",
    "PhysicalReceipt",
    "PassiveWakeAdmission",
    "PassiveWakeSignal",
    "PortfolioTransitionResult",
    "SignalAspTransitionError",
    "SignalPassiveWakeAdmission",
    "ProviderConformanceCaseResult",
    "ProviderConformanceEvidence",
    "ProviderConformanceRun",
    "ProviderConformanceTarget",
    "ProviderContractAttestation",
    "PortfolioBlocker",
    "PortfolioEntry",
    "PortfolioPersistenceError",
    "PortfolioRecoveryReport",
    "PortfolioState",
    "PortfolioStateError",
    "ProviderObservation",
    "ProviderReconciliationContract",
    "ProviderReconciliationEvidence",
    "ProviderReconciliationObservation",
    "ProviderReconciliationQuery",
    "REFERENCE_CAPABILITY",
    "REFERENCE_EVIDENCE",
    "REFERENCE_TASK_KIND",
    "REQUIRED_CORE1_ASSERTIONS",
    "RecoveredLease",
    "ReconciliationDecision",
    "ReconciliationError",
    "RecoveryDriverError",
    "RecoveryDriverResult",
    "ResumeTickError",
    "ResumeTickObservation",
    "ResumeTickResult",
    "ReferenceConformanceTarget",
    "RestartRecoveryReport",
    "ResultEnvelope",
    "RetryPolicy",
    "RetryDecision",
    "RetryAuthorityError",
    "RunnerCapabilities",
    "RunnerCapacityState",
    "RunnerRegistry",
    "SandboxCommandEvidence",
    "SessionError",
    "SessionRecoveryError",
    "SessionRecoveryProjection",
    "SqliteCapacityHeadStore",
    "SqliteDispatchIntentStore",
    "SqliteDurableObservedOutcomeStore",
    "SqlitePortfolioHeadStore",
    "TransitionPolicy",
    "TransitionAuthorityGrant",
    "TransitionPolicyError",
    "TransitionRule",
    "VALID_TRANSPORT_STATUSES",
    "VERCEL_SANDBOX_PROVIDER",
    "VERCEL_SANDBOX_RUNTIME",
    "VERCEL_CORE_VERIFIER_REF",
    "VercelSandboxConformanceError",
    "VercelSandboxConformanceRun",
    "VercelSandboxConformanceSpec",
    "WakeCondition",
    "admit_observation",
    "admit_vercel_core_verification",
    "admit_passive_wake",
    "admit_passive_wake_signal",
    "admit_physical_observation",
    "admit_reconciliation_observation",
    "append_event",
    "apply_recovery_step",
    "apply_asp_transition",
    "apply_active_transition",
    "attest_provider_contract",
    "authorize_attested_resubmission",
    "authorize_live_dispatch",
    "authorize_physical_attempt",
    "authorize_retry",
    "bind_session",
    "build_dispatch_request",
    "build_core_rehearsal_report",
    "canonical_json",
    "capacity_snapshot",
    "capacity_state_from_dict",
    "capacity_state_to_dict",
    "checkpoint_from_dict",
    "checkpoint_to_dict",
    "commit_capacity_reservation",
    "commit_outcome_release",
    "commit_revocation_release",
    "create_reconciliation_query",
    "decide_reconciliation",
    "decide_retry",
    "deserialize_capacity_snapshot",
    "deserialize_checkpoint",
    "deserialize_portfolio_state",
    "deserialize_dispatch_state",
    "deserialize_physical_outcome",
    "deserialize_portfolio_snapshot",
    "deserialize_transition_policy",
    "dispatch_state_from_dict",
    "dispatch_state_to_dict",
    "identify_duplicate_physical_attempt",
    "initial_dispatch_state",
    "initialize_capacity_state",
    "make_reference_observation",
    "match_transition_rule",
    "observe_completed",
    "observe_failure",
    "physical_outcome_from_dict",
    "physical_outcome_to_dict",
    "portfolio_state_from_dict",
    "portfolio_state_to_dict",
    "portfolio_snapshot",
    "plan_execution",
    "prepare_dispatch_intent",
    "project_session_after_restart",
    "propose_capacity_reservation",
    "propose_outcome_release",
    "propose_revocation_release",
    "record_capacity_transition",
    "record_duplicate_physical_attempt",
    "record_invocation",
    "record_physical_attempt",
    "recover_capacity_after_restart",
    "recover_portfolio_after_restart",
    "resume_tick",
    "recover_dispatch_after_restart",
    "reference_runner",
    "release_capacity_for_outcome",
    "release_capacity_for_revocation",
    "release_observed_capacity_after_restart",
    "reserve_capacity",
    "revoke_session",
    "run_provider_conformance",
    "run_vercel_sandbox_conformance",
    "serialize_capacity_snapshot",
    "serialize_checkpoint",
    "serialize_dispatch_state",
    "serialize_physical_outcome",
    "serialize_portfolio_state",
    "serialize_portfolio_snapshot",
    "serialize_transition_policy",
    "sha256_digest",
    "stable_id",
    "start_session",
    "submit_result",
    "transition_policy_from_dict",
    "transition_policy_to_dict",
    "verify_active_lease_grant",
    "verify_attested_resubmission_permit",
    "verify_capacity_release_grant",
    "verify_capacity_state",
    "verify_capacity_transition_record",
    "verify_dispatch_permit",
    "verify_dispatch_recovery",
    "verify_dispatch_request",
    "verify_invocation_bundle",
    "verify_invocation_record",
    "verify_ledger",
    "verify_live_dispatch_permit",
    "verify_physical_attempt_record",
    "verify_physical_outcome",
    "verify_plan",
    "verify_portfolio_recovery",
    "verify_provider_attestation",
    "verify_restart_recovery",
    "verify_retry_chain",
    "verify_vercel_sandbox_conformance_run",
    "PROJECT_ASSURANCE_SYSTEM",
    "RED_TEAM_SYSTEM",
    "IndependentVerificationRequest",
    "IndependentVerificationResponse",
    "RedTeamEscalationRequest",
    "RedTeamResponse",
    "VerificationAdmission",
    "VerificationEscalationError",
    "admit_independent_verification",
    "admit_red_team_response",
    "build_verification_observation",
    "prepare_independent_verification",
    "prepare_red_team_escalation",
]

__version__ = "0.0.13"


# Thin read-only Continuity Check protocol/tool. It observes execution state and
# emits recommendations; it never grants authority or triggers execution.
from .continuity_check import (
    BuildColonyEvidence,
    ConversationAssessment,
    ConversationEvidence,
    ContinuityReport,
    ContinuitySnapshot,
    DevelopmentVerdict,
    DurableStateEvidence,
    EVIDENCE_PRECEDENCE,
    FRESHNESS_RULES,
    FailureScope,
    GateEvidence,
    GateKind,
    InfrastructureStatus,
    ProviderEvidence,
    ProviderState,
    RecommendedAction,
    RepositoryEvidence,
    SCHEMA_VERSION as CONTINUITY_CHECK_SCHEMA_VERSION,
    WorkstreamCandidate,
    WorkstreamResolution,
    inspect_continuity,
    render_report,
    resolve_workstream,
)

__all__.extend([
    "BuildColonyEvidence",
    "ConversationAssessment",
    "ConversationEvidence",
    "ContinuityReport",
    "ContinuitySnapshot",
    "DevelopmentVerdict",
    "DurableStateEvidence",
    "EVIDENCE_PRECEDENCE",
    "FRESHNESS_RULES",
    "FailureScope",
    "GateEvidence",
    "GateKind",
    "InfrastructureStatus",
    "ProviderEvidence",
    "ProviderState",
    "RecommendedAction",
    "RepositoryEvidence",
    "CONTINUITY_CHECK_SCHEMA_VERSION",
    "WorkstreamCandidate",
    "WorkstreamResolution",
    "inspect_continuity",
    "render_report",
    "resolve_workstream",
])


# ELG-01: persistent execution-launch admission. This consumes authenticated
# order/authority evidence and never dispatches work or creates authority.
from .execution_launch_admission import (
    ExecutionLaunchAdmissionError,
    ExecutionLaunchOrder,
    ExecutionLaunchReceipt,
    LaunchAdmissionResult,
    LaunchAuthorityBinding,
    LaunchExecutorBinding,
    admit_execution_launch_order,
    admit_or_replay_execution_launch,
    execution_launch_order_from_dict,
    execution_launch_receipt_from_dict,
    launch_order_to_dict,
    launch_receipt_to_dict,
)

__all__.extend([
    "ExecutionLaunchAdmissionError",
    "ExecutionLaunchOrder",
    "ExecutionLaunchReceipt",
    "LaunchAdmissionResult",
    "LaunchAuthorityBinding",
    "LaunchExecutorBinding",
    "admit_execution_launch_order",
    "admit_or_replay_execution_launch",
    "execution_launch_order_from_dict",
    "execution_launch_receipt_from_dict",
    "launch_order_to_dict",
    "launch_receipt_to_dict",
])


# EAC-01: receipt-bound executor activation. This consumes only ADMITTED
# ELG-01 receipts, preserves executor-native ownership, and never creates authority.
from .executor_activation import (
    ExecutorActivationAdapter,
    ExecutorActivationCapability,
    ExecutorActivationError,
    ExecutorActivationIntent,
    ExecutorActivationResult,
    ExecutorActivationState,
    NativeActivationObservation,
    SqliteExecutorActivationStore,
    activate_or_reconcile_executor,
    activation_state_from_dict,
    activation_state_to_dict,
    begin_activation,
    deserialize_activation_state,
    initial_activation_state,
    observe_activation,
    prepare_executor_activation,
    serialize_activation_state,
)
from .continuity_check import (
    ExecutorActivationDisposition,
    ExecutorActivationEvidence,
)

__all__.extend([
    "ExecutorActivationAdapter",
    "ExecutorActivationCapability",
    "ExecutorActivationDisposition",
    "ExecutorActivationError",
    "ExecutorActivationEvidence",
    "ExecutorActivationIntent",
    "ExecutorActivationResult",
    "ExecutorActivationState",
    "NativeActivationObservation",
    "SqliteExecutorActivationStore",
    "activate_or_reconcile_executor",
    "activation_state_from_dict",
    "activation_state_to_dict",
    "begin_activation",
    "deserialize_activation_state",
    "initial_activation_state",
    "observe_activation",
    "prepare_executor_activation",
    "serialize_activation_state",
])


# Receipt-bound Work escalation bridge. This binds Work-Sparse selection to
# durable budget/admission identity and external provider evidence; it does not
# launch Work or create authority by itself.
from .work_escalation_bridge import (
    AUTHORITY_SCHEMA as WORK_INVOCATION_AUTHORITY_SCHEMA,
    PLATFORM_OBSERVATION_SCHEMA as WORK_PLATFORM_OBSERVATION_SCHEMA,
    PLATFORM_REQUEST_SCHEMA as WORK_PLATFORM_REQUEST_SCHEMA,
    PROTOCOL_VERSION as WORK_ESCALATION_PROTOCOL_VERSION,
    REQUEST_SCHEMA as WORK_ESCALATION_REQUEST_SCHEMA,
    STATE_SCHEMA as WORK_ESCALATION_STATE_SCHEMA,
    ExternalWorkExecutorActivationAdapter,
    SqliteWorkEscalationStore,
    WorkEscalationBudgetExhausted,
    WorkEscalationError,
    WorkEscalationRequest,
    WorkEscalationState,
    WorkInvocationAuthority,
    WorkPlatformActivationRequest,
    WorkPlatformObservation,
    build_work_launch_order,
    prepare_work_escalation_request,
    prepare_work_platform_activation_request,
    record_work_platform_observation,
    work_executor_capability,
    work_platform_activation_request_from_dict,
    work_platform_activation_request_to_dict,
    work_platform_observation_from_dict,
    work_platform_observation_to_dict,
)

__all__.extend([
    "WORK_INVOCATION_AUTHORITY_SCHEMA",
    "WORK_PLATFORM_OBSERVATION_SCHEMA",
    "WORK_PLATFORM_REQUEST_SCHEMA",
    "WORK_ESCALATION_PROTOCOL_VERSION",
    "WORK_ESCALATION_REQUEST_SCHEMA",
    "WORK_ESCALATION_STATE_SCHEMA",
    "ExternalWorkExecutorActivationAdapter",
    "SqliteWorkEscalationStore",
    "WorkEscalationBudgetExhausted",
    "WorkEscalationError",
    "WorkEscalationRequest",
    "WorkEscalationState",
    "WorkInvocationAuthority",
    "WorkPlatformActivationRequest",
    "WorkPlatformObservation",
    "build_work_launch_order",
    "prepare_work_escalation_request",
    "prepare_work_platform_activation_request",
    "record_work_platform_observation",
    "work_executor_capability",
    "work_platform_activation_request_from_dict",
    "work_platform_activation_request_to_dict",
    "work_platform_observation_from_dict",
    "work_platform_observation_to_dict",
])
