"""General Execution: deterministic execution substrate for bounded authorized work."""

from .adapter import (
    AdapterDispatchRequest,
    AdapterError,
    AdapterReceipt,
    InvocationBundle,
    ProviderObservation,
    REFERENCE_CAPABILITY,
    REFERENCE_EVIDENCE,
    REFERENCE_TASK_KIND,
    admit_observation,
    build_dispatch_request,
    make_reference_observation,
    reference_runner,
    verify_dispatch_request,
    verify_invocation_bundle,
)
from .canonical import canonical_json, sha256_digest, stable_id
from .ledger import ExecutionLedger, LedgerEvent, append_event, verify_ledger
from .models import (
    ArtifactRef,
    DispatchPlan,
    ExecutionSession,
    ExecutionSpec,
    ResultEnvelope,
    RunnerCapabilities,
    RunnerRegistry,
)
from .physical import (
    DuplicatePhysicalAttempt,
    FAILURE_TRANSPORT_STATUSES,
    PhysicalAttemptAuthorization,
    PhysicalAttemptError,
    PhysicalAttemptRecord,
    PhysicalObservation,
    PhysicalOutcomeBundle,
    PhysicalReceipt,
    VALID_TRANSPORT_STATUSES,
    admit_physical_observation,
    authorize_physical_attempt,
    authorize_retry,
    identify_duplicate_physical_attempt,
    observe_completed,
    observe_failure,
    record_duplicate_physical_attempt,
    record_physical_attempt,
    verify_physical_attempt_record,
    verify_physical_outcome,
    verify_retry_chain,
)
from .planner import plan_execution, verify_plan
from .provenance import InvocationRecord, record_invocation, verify_invocation_record
from .session import SessionError, bind_session, revoke_session, start_session, submit_result

__all__ = [
    "AdapterDispatchRequest",
    "AdapterError",
    "AdapterReceipt",
    "ArtifactRef",
    "DispatchPlan",
    "DuplicatePhysicalAttempt",
    "ExecutionLedger",
    "ExecutionSession",
    "ExecutionSpec",
    "FAILURE_TRANSPORT_STATUSES",
    "InvocationBundle",
    "InvocationRecord",
    "LedgerEvent",
    "PhysicalAttemptAuthorization",
    "PhysicalAttemptError",
    "PhysicalAttemptRecord",
    "PhysicalObservation",
    "PhysicalOutcomeBundle",
    "PhysicalReceipt",
    "ProviderObservation",
    "REFERENCE_CAPABILITY",
    "REFERENCE_EVIDENCE",
    "REFERENCE_TASK_KIND",
    "ResultEnvelope",
    "RunnerCapabilities",
    "RunnerRegistry",
    "SessionError",
    "VALID_TRANSPORT_STATUSES",
    "admit_observation",
    "admit_physical_observation",
    "append_event",
    "authorize_physical_attempt",
    "authorize_retry",
    "bind_session",
    "build_dispatch_request",
    "canonical_json",
    "identify_duplicate_physical_attempt",
    "make_reference_observation",
    "observe_completed",
    "observe_failure",
    "plan_execution",
    "record_duplicate_physical_attempt",
    "record_invocation",
    "record_physical_attempt",
    "reference_runner",
    "revoke_session",
    "sha256_digest",
    "stable_id",
    "start_session",
    "submit_result",
    "verify_dispatch_request",
    "verify_invocation_bundle",
    "verify_invocation_record",
    "verify_ledger",
    "verify_physical_attempt_record",
    "verify_physical_outcome",
    "verify_plan",
    "verify_retry_chain",
]

__version__ = "0.0.3"
